
[dependencies]

[dependencies.crypto]
git = "github.com/amalgame-lang/amalgame-crypto"
tag = "v0.8.0"

[dependencies.datetime]
git = "github.com/amalgame-lang/amalgame-datetime"
tag = "v0.2.2"

[dependencies.random]
git = "github.com/amalgame-lang/amalgame-random"
tag = "v0.1.0"

[dependencies.logging]
git = "github.com/amalgame-lang/amalgame-logging"
tag = "v0.2.0"

[dependencies.web]
git = "github.com/amalgame-lang/amalgame-web"
tag = "v0.36.4"
